# Proyecto
## **ING200** - OPTIMIZACIÓN
***Prof**. Jorge Acuña, Ph.D.*

**Integrantes:** *Simón Valdés, Vicente Díaz*

**Fecha:** *Ns*

*Universidad Adolfo Ibáñez*

*Viña del Mar, Chile*

In [42]:
import pandas as pd
from gurobipy import GRB
import gurobipy as gp
import matplotlib as plt

Para procesar el archivo de datos en Excel lo convertimos a dos archivos CSV, uno por cada tabla. Los cargamos como Data Frames a continuación.

In [43]:
operaciones = pd.read_csv("data/Operaciones.csv", sep=";")
permitidas = pd.read_csv("data/Operaciones_Permitidas.csv", sep=",")

In [44]:
# tratar datos de operaciones
#cambiamos coma por punto y pasamos a float
operaciones["Duracion_Horas"] = operaciones["Duracion_Horas"].str.replace(",", ".").astype(float)
#quitamos espacios y pasamos a entero
operaciones["Costo ($)"] = operaciones["Costo ($)"].str.replace(' ', '').astype(int)

operaciones.head()

  ID_Operacion  Duracion_Horas            Tipo  Costo ($)
0        OP001             3.5  Traumatológica    2910051
1        OP002             1.0     Neurológica    3270018
2        OP003             1.5        Gástrica    1840015
3        OP004             1.5  Traumatológica    2080043
4        OP005             3.5        Vascular    3800018

In [45]:
#tratar los datos de permitidas
#hay que convertir en una lista la columna de operaciones permitidas
permitidas['Tipos de operaciones permitidas'] = permitidas['Tipos de operaciones permitidas'].str.split(';')

permitidas.head()

     Pabellón                    Tipos de operaciones permitidas
0  Pabellón_1  [Dérmica, Ginecológica, Otorrinolaringológica,...
1  Pabellón_2       [Vascular, Urológica, Gástrica, Neurológica]
2  Pabellón_3  [Gástrica, Neurológica, Urológica, Oftalmológi...
3  Pabellón_4  [Otorrinolaringológica, Vascular, Ginecológica...
4  Pabellón_5          [Gástrica, Traumatológica, Oftalmológica]